import{a as L,i as l,S as w}from"./assets/vendor-6e0bf343.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();function p(t){return t.map(({webformatURL:r,tags:a,largeImageURL:s,likes:e,views:o,comments:n,downloads:u})=>` <li class="gallery-item">
        <a class="gallery-link" href="${s}" >
          <img class="gallery-image"
           src="${r}" 
           alt="${a}" 
           width = "360"/>
          <ul class="card-descr">
           <li class="card-element"><span class="label">Likes</span> <p class ="value">${e}</p></li>
            <li class="card-element"><span class="label">Views</span> <p class ="value">${o}</p></li>
            <li class="card-element"><span class="label">Comments</span> <p class ="value">${n}</p></li>
            <li class="card-element"><span class="label">Downloads</span><p class ="value">${u}</p></li></ul>
        </a>
      </li>`).join("")}const C="43193709-9f2e77a8cd9049868dd3fabee";async function g(t,r="1"){const a={key:C,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:15};try{const s=await L.get("https://pixabay.com/api/",{params:a});if(s.status!==200)throw new Error(s.statusText);return s.data}catch(s){throw s}}const m=document.querySelector(".search-form"),c=document.querySelector(".gallery"),S=document.querySelector(".search-btn"),f=document.querySelector(".loader"),i=document.querySelector(".load-more");i.addEventListener("click",v);S.addEventListener("click",b);m.addEventListener("submit",b);let d=1;function h(){f.style.display="block"}function y(){f.style.display="none"}function b(t){t.preventDefault();const a=document.querySelector(".search-form input").value.trim();if(a===""){l.show({message:"Please enter a search query",messageColor:" #fff",backgroundColor:"#ef4040",position:"topCenter",messageSize:"16px",messageLineHeight:"150%",iconColor:"white"});return}h(),c.innerHTML="",g(a).then(s=>{if(s.hits.length===0)l.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:" #fff",backgroundColor:"#ef4040",position:"topCenter",messageSize:"16px",messageLineHeight:"150%",iconColor:"white"});else{c.innerHTML=p(s.hits);const e={captionDelay:250,captionsData:"alt",captionPosition:"bottom"};new w(".gallery a",e).refresh();const n=15,u=Math.ceil(s.total/n);d<u&&i.classList.replace("load-hidden","load-more")}}).catch(s=>{c.innerHTML="",l.show({message:"An error occurred while fetching images. Please try again later.",messageColor:" #fff",backgroundColor:"#ef4040",position:"topCenter",messageSize:"16px",messageLineHeight:"150%",iconColor:"white"})}).finally(()=>{y(),m.reset()})}async function v(){h(),i.disabled=!0;try{d++;const t=await g(d);t&&t.hits&&t.hits.length>0?(c.insertAdjacentHTML("beforeend",p(t.hits)),i.disabled=!1,t.page>=t.totalPages&&(i.classList.replace("load-more","load-hidden"),l.show({message:"We're sorry, but you've reached the end of search results.",messageColor:" #fff",backgroundColor:"#ef4040",position:"topCenter",messageSize:"16px",messageLineHeight:"150%",iconColor:"white"}))):i.style.display="none"}catch{}finally{y()}}function x(){const t=document.querySelector(".gallery a");if(t){const r=t.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}x();
//# sourceMappingURL=commonHelpers.js.map
